# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"

#  config.vbguest.auto_update = false
  config.omnibus.chef_version = :latest 
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  config.vm.provision "shell", inline: <<-SHELL
     yum update -y
   SHELL
  config.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "~/my_repo/chef_repo/chef_repo/cookbooks"
      chef.add_recipe "java"
      chef.add_recipe "learn_chef_httpd"
      chef.json = {
         "java" => {
           "jdk_version" => "7"
          }
        }
    end
end
